# Generated by Django 5.2.11 on 2026-02-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='RSS Feed URL')),
                ('source_type', models.CharField(choices=[('rss', 'RSS Feed'), ('yt', 'YouTube Channel'), ('podcast', 'Podcast')], default='rss', max_length=10)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='news.category')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField()),
                ('guid', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news.source')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
