# Generated by Django 5.2.11 on 2026-02-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='relevance_score',
            field=models.IntegerField(default=0, help_text='0-100 score based on user interests'),
        ),
    ]
