# Generated by Django 5.2.11 on 2026-02-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_ai_summary_article_relevance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='feedback_score',
            field=models.IntegerField(default=0),
        ),
    ]
