# Generated by Django 5.2.11 on 2026-02-13 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_feedback_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, help_text='Channel/Podcast author', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='content_depth',
            field=models.CharField(choices=[('light', 'Light/Quick Read'), ('medium', 'Medium Depth'), ('heavy', 'Deep/Long-form')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='duration_seconds',
            field=models.IntegerField(blank=True, help_text='Video/podcast duration', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='personalization_score',
            field=models.FloatField(default=0.0, help_text='Personalized score combining AI + user preferences'),
        ),
        migrations.AddField(
            model_name='article',
            name='serendipity_score',
            field=models.FloatField(default=0.0, help_text='Score for unexpected but potentially interesting content'),
        ),
        migrations.AddField(
            model_name='article',
            name='trend_score',
            field=models.FloatField(default=0.0, help_text='Market trend/importance score'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReadingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Morning Briefing', 'Deep Dive', 'Light Reading'", max_length=100)),
                ('content_depth', models.CharField(choices=[('light', 'Light Content Only'), ('medium', 'Mixed'), ('heavy', 'Deep Content Only')], default='medium', max_length=20)),
                ('relevance_weight', models.FloatField(default=0.6, help_text='Weight for AI relevance score')),
                ('personalization_weight', models.FloatField(default=0.3, help_text='Weight for personalization')),
                ('serendipity_weight', models.FloatField(default=0.1, help_text='Weight for serendipity')),
                ('trend_weight', models.FloatField(default=0.2, help_text='Weight for trending topics')),
                ('is_active', models.BooleanField(default=False)),
                ('enabled_categories', models.ManyToManyField(blank=True, to='news.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_keywords', models.JSONField(default=list, help_text='List of interest keywords')),
                ('preferred_categories', models.JSONField(default=dict, help_text='Dict of category_slug -> weight')),
                ('preferred_sources', models.JSONField(default=dict, help_text='Dict of source_id -> weight')),
                ('preferred_content_depth', models.CharField(choices=[('light', 'Prefer Light Content'), ('medium', 'Balanced'), ('heavy', 'Prefer Deep Dives')], default='medium', max_length=20)),
                ('current_mood', models.CharField(default='balanced', help_text='Current reading mood', max_length=50)),
                ('total_feedback_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
