# Generated by Django 5.2.11 on 2026-02-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_convert_textfield_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingcontext',
            name='relevance_weight',
            field=models.FloatField(default=0.5, help_text='Weight for AI relevance score'),
        ),
        migrations.AlterField(
            model_name='readingcontext',
            name='serendipity_weight',
            field=models.FloatField(default=0.05, help_text='Weight for serendipity'),
        ),
        migrations.AlterField(
            model_name='readingcontext',
            name='trend_weight',
            field=models.FloatField(default=0.15, help_text='Weight for trending topics'),
        ),
    ]
